from __future__ import annotations

from typing import Any, Dict, List, Optional

from backend.llm.ollama_client import OllamaClient
from backend.llm.prompts import build_optimize_messages
from backend.rag.retriever import KnowledgeRetriever
from backend.schemas.api import OptimizeRequest, OptimizeResponse, OptimizeSuggestion
from backend.services.telemetry_service import TelemetryService


class OptimizeService:
    """Service layer for optimize API requests.

    This service uses retrieval, prompt building and LLM responses to suggest
    performance and cost optimizations for code and queries.
    """

    def __init__(
        self,
        retriever: Optional[KnowledgeRetriever] = None,
        llm_client: Optional[OllamaClient] = None,
        telemetry: Optional[TelemetryService] = None,
    ) -> None:
        self._retriever = retriever or KnowledgeRetriever()
        self._llm_client = llm_client or OllamaClient()
        self._telemetry = telemetry or TelemetryService()

    def _build_context_dict(self, request: OptimizeRequest) -> Optional[Dict[str, str]]:
        """Convert OptimizeRequest.context into a simple dict for prompts."""
        if not request.context:
            return None
        return {
            "language": request.context.language or "",
            "framework": request.context.framework or "",
            "cloud_provider": request.context.cloud_provider or "",
        }

    def optimize(self, request: OptimizeRequest) -> OptimizeResponse:
        """Generate optimization suggestions using RAG + LLM.

        Args:
            request: OptimizeRequest containing code, objective and optional context.

        Returns:
            OptimizeResponse: Suggestions with description and examples.
        """
        if not request.code.strip():
            return OptimizeResponse(
                summary="No code was sent for optimization.",
                suggestions=[],
            )

        ctx = self._build_context_dict(request)

        query_text = f"{request.objective or ''}\n\n{request.code}"
        knowledge_hits = self._retriever.retrieve(query=query_text, k=5)

        messages = build_optimize_messages(
            code=request.code,
            objective=request.objective,
            context=ctx,
            retrieved_context=knowledge_hits,
        )

        optimization_text = self._llm_client.chat(messages) or "No optimization suggestions generated."

        suggestions: List[OptimizeSuggestion] = [
            OptimizeSuggestion(
                title="Optimization suggestions",
                description=optimization_text,
                example_before=request.code[:200],
                example_after=None,
                impact=None,
            )
        ]

        user_content = messages[-1]["content"]
        system_content = messages[0]["content"]
        prompt_tokens_estimate = self._telemetry.estimate_tokens_from_text(
            system_content + "\n\n" + user_content
        )
        response_tokens_estimate = self._telemetry.estimate_tokens_from_text(optimization_text)

        self._telemetry.record_event(
            event_type="optimize",
            payload={
                "objective": request.objective,
                "has_code": True,
                "context": ctx,
                "knowledge_hits": len(knowledge_hits),
                "prompt_tokens_estimate": prompt_tokens_estimate,
                "response_tokens_estimate": response_tokens_estimate,
            },
        )

        summary = "Optimization suggestions generated by Samy via Ollama."
        return OptimizeResponse(summary=summary, suggestions=suggestions)