from __future__ import annotations

from typing import Any, Dict, List, Optional

from backend.llm.ollama_client import OllamaClient
from backend.llm.prompts import build_review_messages
from backend.rag.retriever import KnowledgeRetriever
from backend.schemas.api import ReviewRequest, ReviewResponse, ReviewIssue
from backend.services.telemetry_service import TelemetryService


class ReviewService:
    """Service layer for review API requests.

    This service combines retrieval, prompt construction and LLM responses
    to produce structured code reviews.
    """

    def __init__(
        self,
        retriever: Optional[KnowledgeRetriever] = None,
        llm_client: Optional[OllamaClient] = None,
        telemetry: Optional[TelemetryService] = None,
    ) -> None:
        self._retriever = retriever or KnowledgeRetriever()
        self._llm_client = llm_client or OllamaClient()
        self._telemetry = telemetry or TelemetryService()

    def _build_context_dict(self, request: ReviewRequest) -> Optional[Dict[str, str]]:
        """Convert ReviewRequest.context into a simple dict for prompts."""
        if not request.context:
            return None
        return {
            "language": request.context.language or "",
            "framework": request.context.framework or "",
            "cloud_provider": request.context.cloud_provider or "",
        }

    def review(self, request: ReviewRequest) -> ReviewResponse:
        """Generate a code review using RAG + LLM.

        Args:
            request: ReviewRequest containing code, goal and optional context.

        Returns:
            ReviewResponse: Structured review with summary and issues.
        """
        if not request.code.strip():
            return ReviewResponse(
                summary="No code was sent for review.",
                issues=[],
            )

        ctx = self._build_context_dict(request)

        query_text = f"{request.goal or ''}\n\n{request.code}"
        knowledge_hits = self._retriever.retrieve(query=query_text, k=5)

        messages = build_review_messages(
            code=request.code,
            goal=request.goal,
            context=ctx,
            retrieved_context=knowledge_hits,
        )

        review_text = self._llm_client.chat(messages) or "No review content generated."

        issues: List[ReviewIssue] = [
            ReviewIssue(
                severity="info",
                message=review_text,
                suggestion=None,
                line=None,
                column=None,
            )
        ]

        user_content = messages[-1]["content"]
        system_content = messages[0]["content"]
        prompt_tokens_estimate = self._telemetry.estimate_tokens_from_text(
            system_content + "\n\n" + user_content
        )
        response_tokens_estimate = self._telemetry.estimate_tokens_from_text(review_text)

        self._telemetry.record_event(
            event_type="review",
            payload={
                "goal": request.goal,
                "has_code": True,
                "context": ctx,
                "knowledge_hits": len(knowledge_hits),
                "prompt_tokens_estimate": prompt_tokens_estimate,
                "response_tokens_estimate": response_tokens_estimate,
            },
        )

        summary = "Code review generated by Samy via Ollama."
        return ReviewResponse(summary=summary, issues=issues)