from __future__ import annotations

from fastapi import APIRouter

from backend.llm.ollama_client import OllamaClient
from backend.llm.prompts import build_optimize_messages
from backend.schemas.api import (
    OptimizeRequest,
    OptimizeResponse,
    OptimizeSuggestion,
)

router = APIRouter(prefix="/optimize", tags=["optimize"])


@router.post("/", response_model=OptimizeResponse, summary="Optimize code or queries")
async def optimize_code(request: OptimizeRequest) -> OptimizeResponse:
    """
    Suggest optimizations for code, SQL or pipelines.

    This endpoint calls the Ollama model to propose performance/cost improvements.
    """
    if not request.code.strip():
        return OptimizeResponse(
            summary="No code was sent for optimization.",
            suggestions=[],
        )

    ctx = None
    if request.context:
        ctx = {
            "language": request.context.language or "",
            "framework": request.context.framework or "",
            "cloud_provider": request.context.cloud_provider or "",
        }

    messages = build_optimize_messages(
        code=request.code,
        objective=request.objective,
        context=ctx,
    )

    client = OllamaClient()
    optimization_text = client.chat(messages)

    suggestions: list[OptimizeSuggestion] = [
        OptimizeSuggestion(
            title="Optimization suggestions",
            description=optimization_text or "No optimization suggestions generated.",
            example_before=request.code[:200],
            example_after=None,
            impact=None,
        )
    ]

    summary = "Optimization suggestions generated by Samy via Ollama."

    return OptimizeResponse(summary=summary, suggestions=suggestions)