from __future__ import annotations

from fastapi import APIRouter

from backend.llm.ollama_client import OllamaClient
from backend.llm.prompts import build_review_messages
from backend.schemas.api import ReviewRequest, ReviewResponse, ReviewIssue

router = APIRouter(prefix="/review", tags=["review"])


@router.post("/", response_model=ReviewResponse, summary="Review code")
async def review_code(request: ReviewRequest) -> ReviewResponse:
    """
    Review a piece of code or SQL and return structured issues and suggestions.

    This endpoint calls the Ollama model to produce a natural language review.
    For now, we return the whole review as a single 'issue' message.
    """
    if not request.code.strip():
        return ReviewResponse(
            summary="No code was sent for review.",
            issues=[],
        )

    ctx = None
    if request.context:
        ctx = {
            "language": request.context.language or "",
            "framework": request.context.framework or "",
            "cloud_provider": request.context.cloud_provider or "",
        }

    messages = build_review_messages(
        code=request.code,
        goal=request.goal,
        context=ctx,
    )

    client = OllamaClient()
    review_text = client.chat(messages)

    issues: list[ReviewIssue] = [
        ReviewIssue(
            severity="info",
            message=review_text or "No review content generated.",
            suggestion=None,
            line=None,
            column=None,
        )
    ]

    summary = "Code review generated by Samy via Ollama."

    return ReviewResponse(summary=summary, issues=issues)