from __future__ import annotations

from typing import Any, Dict, List, Optional

from backend.schemas.api import OptimizeRequest, CodeContext
from backend.services.optimize_service import OptimizeService


class DummyRetriever:
    def __init__(self) -> None:
        self.last_query: Optional[str] = None

    def retrieve(self, *, query: str, k: int = 5) -> List[Dict[str, Any]]:
        self.last_query = query
        return [
            {"content": "opt snippet", "source": "doc.md", "offset": 0},
        ]


class DummyLLMClient:
    def __init__(self) -> None:
        self.last_messages: Optional[List[Dict[str, str]]] = None

    def chat(self, messages: List[Dict[str, str]]) -> str:
        self.last_messages = messages
        return "Dummy optimization"


class DummyTelemetry:
    def __init__(self) -> None:
        self.events: List[Dict[str, Any]] = []

    @staticmethod
    def estimate_tokens_from_text(text: str) -> int:
        return len(text.split())

    def record_event(self, event_type: str, payload: Dict[str, Any]) -> None:
        self.events.append({"event_type": event_type, "payload": payload})


def test_optimize_service_generates_suggestions_and_telemetry() -> None:
    retriever = DummyRetriever()
    llm_client = DummyLLMClient()
    telemetry = DummyTelemetry()

    service = OptimizeService(
        retriever=retriever,
        llm_client=llm_client,
        telemetry=telemetry,
    )

    request = OptimizeRequest(
        code="SELECT * FROM big_table;",
        objective="performance",
        context=CodeContext(language="sql"),
    )

    response = service.optimize(request)

    assert response.summary == "Optimization suggestions generated by Samy via Ollama."
    assert len(response.suggestions) == 1
    assert response.suggestions[0].description == "Dummy optimization"
    assert retriever.last_query is not None
    assert "performance" in retriever.last_query

    assert llm_client.last_messages is not None
    assert len(telemetry.events) == 1
    event = telemetry.events[0]
    assert event["event_type"] == "optimize"
    payload = event["payload"]
    assert payload["objective"] == "performance"
    assert payload["knowledge_hits"] == 1
    assert "prompt_tokens_estimate" in payload
    assert "response_tokens_estimate" in payload


def test_optimize_service_returns_empty_when_no_code() -> None:
    service = OptimizeService(
        retriever=DummyRetriever(),
        llm_client=DummyLLMClient(),
        telemetry=DummyTelemetry(),
    )

    request = OptimizeRequest(code="", objective=None, context=None)
    response = service.optimize(request)

    assert response.summary == "No code was sent for optimization."
    assert response.suggestions == []