from __future__ import annotations

from typing import Any, Dict, List, Optional

from backend.schemas.api import ReviewRequest, CodeContext
from backend.services.review_service import ReviewService


class DummyRetriever:
    def __init__(self) -> None:
        self.last_query: Optional[str] = None

    def retrieve(self, *, query: str, k: int = 5) -> List[Dict[str, Any]]:
        self.last_query = query
        return [
            {"content": "review snippet", "source": "doc.md", "offset": 0},
        ]


class DummyLLMClient:
    def __init__(self) -> None:
        self.last_messages: Optional[List[Dict[str, str]]] = None

    def chat(self, messages: List[Dict[str, str]]) -> str:
        self.last_messages = messages
        return "Dummy review"


class DummyTelemetry:
    def __init__(self) -> None:
        self.events: List[Dict[str, Any]] = []

    @staticmethod
    def estimate_tokens_from_text(text: str) -> int:
        return len(text.split())

    def record_event(self, event_type: str, payload: Dict[str, Any]) -> None:
        self.events.append({"event_type": event_type, "payload": payload})


def test_review_service_generates_review_and_telemetry() -> None:
    retriever = DummyRetriever()
    llm_client = DummyLLMClient()
    telemetry = DummyTelemetry()

    service = ReviewService(
        retriever=retriever,
        llm_client=llm_client,
        telemetry=telemetry,
    )

    request = ReviewRequest(
        code="SELECT * FROM users;",
        goal="performance",
        context=CodeContext(language="sql"),
    )

    response = service.review(request)

    assert response.summary == "Code review generated by Samy via Ollama."
    assert len(response.issues) == 1
    assert response.issues[0].message == "Dummy review"
    assert retriever.last_query is not None
    assert "performance" in retriever.last_query

    assert llm_client.last_messages is not None
    assert len(telemetry.events) == 1
    event = telemetry.events[0]
    assert event["event_type"] == "review"
    payload = event["payload"]
    assert payload["goal"] == "performance"
    assert payload["knowledge_hits"] == 1
    assert "prompt_tokens_estimate" in payload
    assert "response_tokens_estimate" in payload


def test_review_service_returns_empty_when_no_code() -> None:
    service = ReviewService(
        retriever=DummyRetriever(),
        llm_client=DummyLLMClient(),
        telemetry=DummyTelemetry(),
    )

    request = ReviewRequest(code="", goal=None, context=None)
    response = service.review(request)

    assert response.summary == "No code was sent for review."
    assert response.issues == []