from __future__ import annotations

from fastapi.testclient import TestClient

from backend.main import create_app


client = TestClient(create_app())


def test_review_with_code_returns_issues(monkeypatch) -> None:
    import backend.llm.ollama_client as ollama_module

    def fake_chat(messages):
        return "Fake review content."

    monkeypatch.setattr(ollama_module.OllamaClient, "chat", lambda self, messages: fake_chat(messages))

    payload = {
        "code": "def foo():\n    return 1",
        "goal": "clean code",
    }
    resp = client.post("/review", json=payload)
    assert resp.status_code == 200
    body = resp.json()
    assert body["summary"] == "Code review generated by Samy via Ollama."
    assert isinstance(body["issues"], list)
    assert len(body["issues"]) == 1
    issue = body["issues"][0]
    assert issue["severity"] == "info"
    assert issue["message"] == "Fake review content."


def test_review_without_code_returns_empty_issues() -> None:
    payload = {"code": "", "goal": None}
    resp = client.post("/review", json=payload)
    assert resp.status_code == 200
    body = resp.json()
    assert body["summary"] == "No code was sent for review."
    assert body["issues"] == []