from __future__ import annotations

from fastapi.testclient import TestClient

from backend.main import create_app


client = TestClient(create_app())


def test_review_with_code_returns_issues(monkeypatch) -> None:
    import backend.llm.ollama_client as ollama_module
    from backend.rag import vector_store as vector_store_module

    # Mock LLM chat
    def fake_chat(messages):
        return "Fake review content."

    monkeypatch.setattr(ollama_module.OllamaClient, "chat", lambda self, messages: fake_chat(messages))
    monkeypatch.setattr(ollama_module.OllamaClient, "embeddings", lambda self, text: [0.1, 0.2])

    # Mock VectorStore to avoid real Chroma calls
    class DummyVectorStore:
        def query(self, *, query_text: str, k: int = 5):
            return [
                {"content": "rag snippet", "source": "doc.md", "offset": 0},
            ]

    monkeypatch.setattr(
        vector_store_module, "VectorStore", lambda collection_name="samy_knowledge": DummyVectorStore()
    )

    payload = {
        "code": "def foo():\n    return 1",
        "goal": "clean code",
    }
    resp = client.post("/review", json=payload)
    
    assert resp.status_code == 200
    body = resp.json()
    assert body["summary"] == "Code review generated by Samy via Ollama."
    assert isinstance(body["issues"], list)
    assert len(body["issues"]) == 1
    issue = body["issues"][0]
    assert issue["severity"] == "info"
    assert issue["message"] == "Fake review content."