from __future__ import annotations

from fastapi.testclient import TestClient

from backend.main import create_app


client = TestClient(create_app())


def test_optimize_with_code_returns_suggestions(monkeypatch) -> None:
    import backend.llm.ollama_client as ollama_module
    from backend.rag import vector_store as vector_store_module

    def fake_chat(messages):
        return "Fake optimization suggestions."

    monkeypatch.setattr(ollama_module.OllamaClient, "chat", lambda self, messages: fake_chat(messages))
    monkeypatch.setattr(ollama_module.OllamaClient, "embeddings", lambda self, text: [0.1, 0.2])

    class DummyVectorStore:
        def query(self, *, query_text: str, k: int = 5):
            return [
                {"content": "rag snippet", "source": "doc.md", "offset": 0},
            ]

    monkeypatch.setattr(
        vector_store_module, "VectorStore", lambda collection_name="samy_knowledge": DummyVectorStore()
    )

    payload = {
        "code": "SELECT * FROM big_table;",
        "objective": "performance",
    }
    resp = client.post("/optimize", json=payload)
    assert resp.status_code == 200
    body = resp.json()
    assert body["summary"] == "Optimization suggestions generated by Samy via Ollama."
    assert isinstance(body["suggestions"], list)
    assert len(body["suggestions"]) == 1
    suggestion = body["suggestions"][0]
    assert suggestion["title"] == "Optimization suggestions"
    assert suggestion["description"] == "Fake optimization suggestions."
    assert suggestion["example_before"] == "SELECT * FROM big_table;"


def test_optimize_without_code_returns_empty_suggestions() -> None:
    payload = {"code": "", "objective": None}
    resp = client.post("/optimize", json=payload)
    assert resp.status_code == 200
    body = resp.json()
    assert body["summary"] == "No code was sent for optimization."
    assert body["suggestions"] == []